### ISSUE TITLE
Remove sorting in UpdatesHandler, UpdatesMessageHandler

### ISSUE THREAD

**Issue by KeyboardNerd** [KeyboardNerd/shuttle_tracking_2#1]
Here's the thing, 
I have 10 thousands records in my updates collection and I don't think it's a good idea to sort it for every vehicle, and every request of /updates
err := App.Updates.Find(bson.M{"vehicleID": vehicle.VehicleID}).Sort("-created").Limit(1).One(&update)
Moreover, UpdatesMessageHandler and UpdatesHandler serve similar function
I assume we want Updates collection just for future use of prediction?

**Comment by connection-lost** [comment]
Closed since our solution has changed, this is no longer an issue.
