### ISSUE TITLE
Marker Rotation Problem

### ISSUE THREAD

**Issue by connection-lost** [KeyboardNerd/shuttle_tracking_2#16]
We have a problem. Google maps api does not support png file as marker with rotation. Can anyone think about some workarounds?

ref: https://developers.google.com/maps/documentation/android-api/marker

**Comment by connection-lost** [comment]
For now, I will try converting my png file to a (stupid version of) svg.

**Comment by KeyboardNerd** [comment]
SVG is required by Google API, just do it. I think there are a few sites to do the job...

**Comment by connection-lost** [comment]
SVG will be our solution, code will be updated. We just need a designer :(
