### ISSUE TITLE
ID's data type of Route

### ISSUE THREAD

**Issue by KeyboardNerd** [KeyboardNerd/shuttle_tracking_2#17]
So why it's bson.ObjectId instead of string? If there's no good reason to use bson.ObjectId, I'll change that to string.

**Comment by connection-lost** [comment]
Which file are you talking about?

**Comment by KeyboardNerd** [comment]
Route.go

**Comment by KeyboardNerd** [comment]
I changed the type bson.ObjectId to string and it still works. Since bson.ObjectId is actually defined as 12 bytes long string, maybe using that with care is the best method?
