### ISSUE TITLE
No Delete function in front end for page /admin

### ISSUE THREAD

**Issue by KeyboardNerd** [KeyboardNerd/shuttle_tracking_2#21]
The function doesn't work

**Comment by muryannye** [comment]
When did it not work? Did you put in your own example vehicle and then tried to delete that? If you did, what was it?

**Comment by KeyboardNerd** [comment]
I saw that in tracking-routes.html and tracking-stops.html: deleteRoute, editRoute, deleteStop and editStop functions are not implemented. #15 is the other part of front-end implementation for current functions.
