### ISSUE TITLE
hard coded update interval in shuttles-map.html

### ISSUE THREAD

**Issue by KeyboardNerd** [KeyboardNerd/shuttle_tracking_2#3]
```
  periodicUpdates: function() {
    // periodically check for vehicle & route updates
    setInterval(this.checkForUpdates, 15000, this.$.fetchMessages);
    setInterval(this.checkForUpdates, 15000, this.$.fetchUpdates);
    setInterval(this.checkForUpdates, 15000, this.$.fetchRoutes);
    setInterval(this.checkForUpdates, 15000, this.$.fetchStops);
  },
```

**Comment by connection-lost** [comment]
Will change this to a variable for now. Server need to accomply with the change by sending refreshing interval (fron databse value?) to the client.

**Comment by KeyboardNerd** [comment]
Yes, the clients checkout refresh interval GET from server by dynamically generating a JSON Config. Do we have some configuration file somewhere in the front end?

**Comment by connection-lost** [comment]
This is no longer an issue because we will use dynamic updates with prediction.
