### ISSUE TITLE
Latest Back-end Code Generates Exception

### ISSUE THREAD

**Issue by connection-lost** [KeyboardNerd/shuttle_tracking_2#33]
pastebin.com/0WduKz7p is the issues, happens every time when clients requests vehicle locations. Is it because front-end is not following up with back-end update?

**Comment by KeyboardNerd** [comment]
No, the current design ( for demo ) is that whenever the client requests updates, computing arrival time in predict.go is triggered. Line 43 in predict.go says it will request the shuttles current traveling segment on the route, and so if the segment is found out of the range ( which is very strange ) then the bug happens. I'm working on refactoring and debugging the demo now.

**Comment by KeyboardNerd** [comment]
Solved by checking if the segment is valid or not.
