### ISSUE TITLE
Deleting vehicles, stops, or routes doesn't actually remove it

### ISSUE THREAD

**Issue by muryannye** [KeyboardNerd/shuttle_tracking_2#35]
Clicking on the delete button successfully removes it from the page. However, when the page is refreshed, the item deleted comes back.

**Comment by KeyboardNerd** [comment]
Sounds like a backend problem, I'll look into it.

**Comment by KeyboardNerd** [comment]
which branch you're working on? The delete function works on vehicles for master branch...

**Comment by connection-lost** [comment]
To update your branch from master branch:
Merge master branch to your branch
