### ISSUE TITLE
Please make sure database file is uploaded to a temporary location

### ISSUE THREAD

**Issue by connection-lost** [KeyboardNerd/shuttle_tracking_2#37]
Although we have database side accomplishment, the initialization part is not complete. In order for people in the future to set up shuttle tracking v2 correctly, please @KeyboardNerd provide a correct database file dump and attach to the readme or upload it here.

**Comment by KeyboardNerd** [comment]
Done, the files are in master branch example_database/, please read readme.txt for detail
