### ISSUE TITLE
Google Maps Lines Don't Complete

### ISSUE THREAD

**Issue by ncwheeler700** [KeyboardNerd/shuttle_tracking_2#38]
The lines in the route creation panel don't seem to be able to connect to make a complete route. When trying to complete the route, it either just goes somewhere close, or it refuses to draw a line at all.

**Comment by KeyboardNerd** [comment]
Basically, the problem comes because the list containing all map points may not have the last point equal to the first point. I'll solve that in the creation of route code.

**Comment by KeyboardNerd** [comment]
solved see pr #43 , if when creating route, the result of interpolation might be wrong due to inaccuracy or low resolution of input coordinates. Generally, putting more points to the map will solve the problem.
