### ISSUE TITLE
This project does not have a license

### ISSUE THREAD

**Issue by connection-lost** [KeyboardNerd/shuttle_tracking_2#42]
The LICENSE file is not a valid license. Ideas anyone?

**Comment by KeyboardNerd** [comment]
MIT license?

**Comment by connection-lost** [comment]
Let's just add MIT to it. Hope they won't get mad about us.

**Comment by connection-lost** [comment]
Okay so here is the thing, we do have MIT license already on the project, but the project failed to state the name of the license...!
